#!/bin/bash

#This script is created for 255.255.255.0 networks only.
#config

#first three numbers of ip with dot at the end (something like: 192.168.1.)
NETWORK=10.0.6.

#should be in output file things like "NEW SCAN" etc.? 0 = false; 1 = true
things=0

#script (dont do anything here, if you do not know what are you doing)
HOST=1
if [ $things -eq 1 ]; then
    echo NEW SCAN >> output.txt
fi
while ((HOST < 255))
do
    echo trying $NETWORK$HOST
    ping -c 1 $NETWORK$HOST
    if [ $? -eq 0 ]; then
        echo $NETWORK$HOST >> output.txt
    else
        echo $NETWORK$HOST is propably dead.
    fi
    let "HOST+=1"
done
if [ $things -eq 1 ]; then    
    echo >> output.txt
fi
# created by filip2cz
# github: https://github.com/filip2cz/network-scan-hosts